ProChat/urls.py
from . import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from app.views import (
	home_screen_view
)

from account.views import (
	account_search,
	login_view,
	logout_view,
	register_view,
)

urlpatterns = [
    path('', home_screen_view, name='home'),
	
    path('account/', include('account.urls', namespace='account')),

    path('admin/', admin.site.urls),

    path('chat/', include('chat.urls', namespace='chat')),

    path('friend/', include('friend.urls', namespace='friend')),

    path('login/', login_view, name='login'),

    path('logout/', logout_view, name='logout'),

    path('register/', register_view, name='register'),

    path('search/', account_search, name='search'),


    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from account.views import (
	account_view,
	edit_acc_view,
	crop_image,
)

app_name = 'account'

urlpatterns = [
	path('<user_id>/', account_view, name='view'),
	path('<user_id>/edit/', edit_acc_view, name='edit'),
	path('<user_id>/edit/crop/', crop_image, name='crop'),
]

chat/urls.py
from django.urls import path
from .views import (
	private_chat_room_view,
	create_private_chat
)


app_name = 'chat'


urlpatterns = [
	path('', private_chat_room_view, name='private-chat-room'),
	path('private-chat/', create_private_chat, name='create-private-chat'),
]

templates/snippets/base_css.html
<style type="text/css">
	head {
		font-family: 'Segoe UI';
		font-weight: 380;
	}
	footer {
		font-family: 'Segoe UI';
		font-weight: 380;
	}
	body {
		background-color: #f2f2f2;
		font-family: 'Segoe UI';
		font-weight: 380;
	}
	:root {
		--main-background-color: #f2f2f2;
		--dark-background-color: #a2a2a2;
		--secondary-text-color: #808080;
		--light-primary-text-color: #0080ff;
	}
</style>

templates/snippets/base_js.html
<script type="text/javascript" lang="javascript">

</script>

templates/snippets/chat_notifications.html
{% load static %}

<style type="text/css">
	.notification-thumbnail-image{
		height: 50px;
		width: 50px;
	}
	.chat-card:hover{
		cursor: pointer;
		background: #f2f2f2;
	}
	.chat-card{
		border-bottom: 1px solid var(--main-background-color);
	}
	.timestamp-text{
		color: var(--secondary-text-color);
	}
	.notification-chatroom-msg{
		color: var(--light-primary-text-color);
	}
	.chat-dropdown-header{
		color: var(--light-primary-text-color);
	}
</style>

<p id="id_chat_newest_timestamp"></p>
<p id="id_chat_page_number">1</p>

<script src="{% static 'collections/collections.min.js' %}"></script>

<script lang="javascript" type="text/javascript">

	setOnChatNotificationScrollListener();
	onChatNotificationsPaginationTriggerListener();

	const CHAT_NOTIFICATION_INTERVAL = 4000;

	var chatCacheNotifList = new List([]);

	function submitNewChatNotificationToCache(notification){
		var result = chatCacheNotifList.filter(function(n){ 
			return n['notification_id'] === notification['notification_id'];
		});
		if(result.length == 0){
			chatCacheNotifList.push(notification);
			appendTopChatNotification(notification);
		}
		else{
			refreshChatNotificationsList(notification);
		}
	}

	function submitChatNotificationToCache(notification){
		var result = chatCacheNotifList.filter(function(n){ 
			return n['notification_id'] === notification['notification_id'];
		});
		if(result.length == 0){
			chatCacheNotifList.push(notification);
			appendBottomChatNotification(notification);
		}
		else{
			refreshChatNotificationsList(notification);
		}
	}

	function handleNewChatNotificationsData(notifications){
		console.log("\n\nin handleNewChatNotificationsData\n\n"+notifications.length);
		if(notifications.length > 0){
			clearNoChatNotificationsCard();
			notifications.forEach(notification => {
				submitNewChatNotificationToCache(notification);
				setChatNewestTimestamp(notification['timestamp']);
			});
		}
	}

	function handleChatNotificationsData(notifications, new_page_number) {
		console.log("\n\nin handleChatNotificationsData\n\n"+notifications.length);
		if(notifications.length > 0){
			clearNoChatNotificationsCard();
			notifications.forEach(notification => {
				submitChatNotificationToCache(notification);
				setChatNewestTimestamp(notification["timestamp"]);
			});
			setChatPageNumber(new_page_number);
		}
	}

	function setChatNewestTimestamp(timestamp) {
		const elm = document.getElementById("id_chat_newest_timestamp");
		var cur = elm.innerText;
		if(Date.parse(timestamp) > Date.parse(cur)) {
			elm.innerText = timestamp;
		}
		else if(cur == "" || cur == null || cur == "undefined") {
			elm.innerText = timestamp;
		}
	}

	function setupChatDropdownHeader() {
		var notificationContainer = document.getElementById("id_chat_notifications_container");

		if (notificationContainer != null) {

			var div = document.createElement("div");
			div.classList.add("chat-dropdown-header", "d-flex", "flex-row", "justify-content-end", "my-2", "mr-2");
			div.addEventListener("click", function (e) {
				var url = "{% url 'chat:private-chat-room' %}";
				chatRedirect(url);
			});

			span1 = document.createElement("span");
			span1.innerText = "Go to chat";
			div.appendChild(span1);

			span2 = document.createElement("span");
			span2.classList.add("material-icons", "ml-2");
			span2.innerText = "open_with";
			div.appendChild(span2);
			notificationContainer.appendChild(div);

			span1.style.cursor = span2.style.cursor = "default";
		}
	}

	function chatRedirect(url) {
		window.location.href = url;
	}

	function setupChatNotificationsMenu() {
		var notificationContainer = document.getElementById("id_chat_notifications_container");
		if(notificationContainer != null) {
			setupChatDropdownHeader();
			const card = createChatNotificationsCard("id_no_chat_notifications");

			var div = document.createElement("div");
			div.setAttribute("class", "d-flex flex-row align-items-start");

			var span = document.createElement("span");
			span.setAttribute("class", "align-items-center pt-1 m-auto");
			span.innerText = "No Notifications Yet";
			div.appendChild(span);
			card.appendChild(div);
			notificationContainer.appendChild(card);
			setChatNotificationsCount([]);
		}
	}

	function clearNoChatNotificationsCard() {
		const elm = document.getElementById("id_no_chat_notifications");
		if(elm != null && elm != "undefined") {
			document.getElementById("id_chat_notifications_container").removeChild(elm);
		}
	}

	function createChatNotificationsCard(cardID) {
		var card = document.createElement("div");
		if(card != "undefined") {
			card.id = cardID;
			card.setAttribute("class", "d-flex flex-column chat-card p-2");
			return card;
		}
	}

	function createChatProfileImage(notification) {
		var img = document.createElement("img");
		img.setAttribute("class", "notification-thumbnail-image img-fluid rounded-circle mr-2");
		img.src = "{% static 'ProChat/dummy_image.png' %}";
		img.id = assignChatImgId(notification["notification_id"]);
		return img;
	}

	function createChatTimestampElement(notification) {
		var ts = document.createElement("p");
		ts.setAttribute("class", "small pt-2 timestamp-text m-auto");
		ts.innerText = notification["natural_timestamp"];
		ts.id = assignChatTimestampId(notification);
		return ts;
	}

	function createUnseenChatRoomMessagesElement(notification) {
		const card = createChatNotificationsCard();
		card.id = assignChatCardId(notification)
		card.addEventListener("click", function(){
			let url = notification['actions']['redirect_url']
			url = url.substr(0, url.length-1)
			chatRedirect(url);
		});

		var div1 = document.createElement("div");
		div1.classList.add("d-flex", "flex-row", "align-items-start");
		div1.id = assignChatDiv1Id(notification);

		const img = createChatProfileImage(notification);
		img.id = assignChatImgId(notification);
		div1.appendChild(img);

		var div2 = document.createElement("div");
		div2.classList.add("d-flex", "flex-column");
		div2.id = assignChatDiv2Id(notification);
		
		var title = document.createElement("span");
		title.classList.add("align-items-start");
		title.innerText = notification['from']['title'];
		title.id = assignChatTitleId(notification);
		div2.appendChild(title);

		var chatRoomMessage = document.createElement("span");
		chatRoomMessage.id = assignChatroomMessageId(notification);
		chatRoomMessage.classList.add("align-items-start", "pt-1", "small", "notification-chatroom-msg");
		if(notification['verb'].length > 50){
			chatRoomMessage.innerText = notification['verb'].slice(0, 50) + "...";
		}
		else{
			chatRoomMessage.innerText = notification['verb'];
		}
		div2.appendChild(chatRoomMessage);
		div1.appendChild(div2);
		card.appendChild(div1);
		card.appendChild(createChatTimestampElement(notification));
		return card;
	}

	function appendTopChatNotification(notification){
		switch(notification['notification_type']) {
			case "UnreadChatRoomMessages":
				var chatNotificationContainer = document.getElementById("id_chat_notifications_container");
				var card = createUnseenChatRoomMessagesElement(notification);
				if(chatNotificationContainer.childNodes.length > 2){
					const index = 2
					chatNotificationContainer.insertBefore(card, chatNotificationContainer.childNodes[index]);
				}
				else {
					chatNotificationContainer.appendChild(card);
				}
				break;
			default:
				break;
		}
	}

	function appendBottomChatNotification(notification){
		switch(notification['notification_type']) {
			case "UnseenChatRoomMessages":
				var chatNotificationContainer = document.getElementById("id_chat_notifications_container");
				var card = createUnseenChatRoomMessagesElement(notification);
				chatNotificationContainer.appendChild(card);
				break;
			default:
				break;
		}
	}

	function refreshUnseenChatRoomMessagesCard(card, notification) {
		card.childNodes.forEach(function(element) {
			if(element.id == ("id_chat_div1_" + notification['notification_id'])) {
				element.childNodes.forEach(function(child) {
					if(child.id == ("id_chat_div2_" + notification['notification_id'])) {
						child.childNodes.forEach(function(nextChild){
							if(nextChild.id == ("id_chat_title_" + notification['notification_id'])) {
								nextChild.innerText = notification['from']['title'];
							}
							if(nextChild.id == ("id_chat_message_" + notification['notification_id'])) {
								if(notification['verb'].length > 50) {
									nextChild.innerText = notification['verb'].slice(0, 50) + "...";
								}
								else{
									nextChild.innerText = notification['verb'];
								}
							}
						});
					}
				});
			}
			if (element.id == ("id_timestamp_" + notification['notification_id'])) {
				element.innerText = notification['natural_timestamp'];
			}
		});
	}

	function refreshChatNotificationsList(notification) {
		var notificationContainer = document.getElementById("id_chat_notifications_container");
		if(notificationContainer != null) {
			var divs = notificationContainer.childNodes;
			divs.forEach(function(card){
				if(card.id == ("id_notification_" + notification['notification_id'])) {
					if(notification['notification_type'] == "UnseenChatRoomMessages"){
						refreshUnseenChatRoomMessagesCard(card, notification);
					}
				}
			});
		}
	}

	function setChatPaginationExhaust() {
		setChatPageNumber("-1");
	}

	function setChatPageNumber(pageNumber) {
		document.getElementById("id_chat_page_number").innerText = pageNumber;
	}

	function onChatNotificationsPaginationTriggerListener() {
		window.onscroll = function(event) {
			if ((window.innerHeight + window.scrollY + 2) >= document.body.scrollHeight) {
				getNextChatNotificationsPage();
			}
		}
	}

	function setOnChatNotificationScrollListener() {
		var menu = document.getElementById("id_chat_notifications_container");
		if(menu != null ) {
			menu.addEventListener("scroll", function(event){
				if ((menu.scrollTop) >= (menu.scrollHeight - menu.offsetHeight)) {
					getNextChatNotificationsPage();
				}
			});
		}
	}

	function setChatNotificationsCount(count){
		var countElement = document.getElementById("id_chat_notifications_count");
		if(count > 0){
			countElement.style.display = "block";
			countElement.innerText = count;
		}
		else{
			countElement.style.background = "transparent";
			countElement.style.display = "none";
		}
	}

	function getUnseenChatNotificationsCount(){
		const pageNum = document.getElementById("id_chat_page_number").innerText;
		if("{{request.user.is_authenticated}}" == "True"){
			ws_notification.send(JSON.stringify({
				"command": "get_unseen_chat_notifications_count"
			}));
		}
	}

	function getNextChatNotificationsPage(){
		const pageNum = document.getElementById("id_chat_page_number").innerText;
		console.log(ws_notification);
		if("{{request.user.is_authenticated}}" == "True" && pageNum != "-1"){
			ws_notification.onopen = function(event) {
				ws_notification.send(JSON.stringify({
					"command": "get_chat_notifications",
					"page_number": pageNum,
				}));
			}
		}
	}

	function getNewChatNotifications(){
		const newestTS = document.getElementById("id_chat_newest_timestamp").innerText;
		if("{{request.user.is_authenticated}}" == "True"){
			ws_notification.send(JSON.stringify({
				"command": "get_new_chat_notifications",
				"newest_timestamp": newestTS,
			}));
		}
	}

	function getFirstChatNotificationsPage(){
		if("{{request.user.is_authenticated}}" == "True"){
			ws_notification.send(JSON.stringify({
				"command": "get_chat_notifications",
				"page_number": "1",
			}));
			getUnseenChatNotificationsCount();
		}
	}

	function startChatNotificationService() {
		if("{{request.user.is_authenticated}}" == "True"){
			setInterval(getFirstChatNotificationsPage, CHAT_NOTIFICATION_INTERVAL);
			setInterval(getNewChatNotifications, CHAT_NOTIFICATION_INTERVAL);
			setInterval(getUnseenChatNotificationsCount, CHAT_NOTIFICATION_INTERVAL);
		}
	}

	startChatNotificationService();

	function assignChatDiv1Id(notification) {
		return "id_chat_div1_" + notification['notification_id'];
	}

	function assignChatImgId(notification) {
		return "id_chat_img_" + notification['notification_id'];
	}

	function assignChatTitleId(notification) {
		return "id_chat_title_" + notification['notification_id'];
	}

	function assignChatroomMessageId(notification) {
		return "id_chat_message_" + notification['notification_id'];
	}

	function assignChatDiv2Id(notification) {
		return "id_chat_div2_" + notification['notification_id'];
	}

	function assignChatTimestampId(notification) {
		return "id_timestamp_" + notification['notification_id'];
	}

	function assignChatCardId(notification) {
		return "id_notification_" + notification['notification_id'];
	}

	function setChatInitialTimestamp() {
		var today = new Date();
		var date = today.getFullYear() + "-01-01 01:00:00.000000";
		document.getElementById("id_chat_newest_timestamp").innerText = date;
	}
	setChatInitialTimestamp();
</script>

templates/snippets/footer.html
{% load static %}

<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
	<p class="m-auto" id="injectYear">
		Live Web Chat App |</p>
</div>



<script type="text/javascript" lang="javascript">
	let date = new Date();
	let footerPTag = document.getElementById("injectYear");
	footerPTag.innerText += ` ${date.getFullYear()}`;
</script>
<!-- End Footer -->

templates/snippets/header.html
{% load static %}

<style type="text/css">
	.chat-dropdown-header{
		color: var(--light-primary-text-color);
		cursor: pointer;
	}
	.scrollable-menu {
		height: auto;
		max-height: 50vh;
		width: max-content;
		overflow-x: hidden;
	}
	#id_general_notifications_container, #id_chat_notifications_container {
		width: 29.3rem;
	}
	.chat-dropdown-header{
		color: var(--light-primary-text-color);
	}
</style>

<!-- Header -->
<div class="d-flex flex-column flex-lg-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
	<div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
		<h5 class="mr-3 font-weight-normal justify-content-start">
			<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>
		<form class="search-bar justify-content-start" onsubmit="return executeQuery()">
			<input type="text" class="form-control" name="q" id="id_q_large" placeholder="Search">
		</form>
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft show p-2">
					<div class="d-flex flex-row">
						<div class="btn-group dropleft">
							<div class="d-flex notifications-icon-container rounded-circle flex-row-reverse mr-3"
								id="id_chat_notification_dropdown_toggle" data-toggle="dropdown">
								<span id="id_chat_notifications_count" class="notify-badge text-danger"></span>
								<span
									class="d-flex material-icons notifications-material-icon m-auto align-items-center">chat</span>
								<div class="dropdown-menu scrollable-menu p-0"
									aria-labelledby="id_chat_notification_dropdown_toggle"
									id="id_chat_notifications_container">
								</div>
							</div>
						</div>
						<div class="btn-group dropleft">
							<div class="d-flex notifications-icon-container rounded-circle flex-row-reverse mr-3"
								id="id_notification_dropdown_toggle" data-toggle="dropdown"
								onclick="setGeneralNotificationsAsSeen()">
								<span id="id_general_notifications_count" class="notify-badge"></span>
								<span
									class="d-flex material-icons notifications-material-icon m-auto align-items-center">notifications</span>
								<div class="dropdown-menu scrollable-menu p-0"
									aria-labelledby="id_notification_dropdown_toggle"
									id="id_general_notifications_container">
								</div>
							</div>
						</div>
						<div class="btn-group dropleft">
							<img class="account-image rounded-circle m-auto d-block dropdown-toggle"
								id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
								src="{{ request.user.profile_image.url }}" alt="User Profile Logo" width="40"
								height="40">
							<div class="dropdown-menu" aria-labelledby="id_profile_links">
								<a class="dropdown-item"
									href="{% url 'account:view' user_id=request.user.username %}">Account</a>
								<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
							</div>
						</div>
					</div>
				</div>
				{% else %}
				<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
				<a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
				{% endif %}
			</nav>
		</div>
	</div>
	<div class="d-flex d-md-none flex-column my-auto align-items-center">
		<h5 class="font-weight-normal">
			<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>
		<form class="search-bar justify-content-start" onsubmit="return executeQuery()">
			<input type="text" class="form-control" name="q" id="id_q_small" placeholder="Search">
		</form>
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft p-2 mt-2">
					<div class="d-flex flex-row">
						<div class="btn-group dropleft">
							<img class="account-image rounded-circle m-auto d-block dropdown-toggle"
								id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
								src="{{ request.user.profile_image.url }}" alt="dummy_image" width="40" height="40">
							<div class="dropdown-menu" aria-labelledby="id_profile_links">
								<a class="dropdown-item"
									href="{% url 'account:view' user_id=request.user.username %}">Account</a>
								<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
							</div>
						</div>
					</div>
				</div>
				{% else %}
				<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
				<a class="btn btn-outline-primary m-2" href="{% url 'register' %}">Register</a>
				{% endif %}
			</nav>
		</div>
	</div>
	<!-- END SMALL SCREENS -->
</div>

{% include 'snippets/general_notifications.html' %}
{% include 'snippets/chat_notifications.html' %}

<script type="text/javascript" lang="javascript">

	const ws_scheme_notification = window.location.protocol === 'https:' ? 'wss' : 'ws';

	const ws_path_notification = `${ws_scheme_notification}://${window.location.host}/`;
	// const ws_path_notification = `${ws_scheme_notification}://${window.location.host}:8001/chat/${room_id}/`;

	const ws_notification = new WebSocket(ws_path_notification);

	ws_notification.onmessage = function(msg) {
		const data = JSON.parse(msg.data);
		console.log(data.chat_msg_type);
		// console.log("Got Gen Chat Notification : " + data.general_msg_type);
		if(data.general_msg_type == 0) {
			handleGeneralNotificationsData(data["notifications"], data["new_page_number"]);
		}
		if(data.general_msg_type == 1) {
			setGeneralPaginationExhausted();
		}
		if(data.general_msg_type == 2) {
			refreshGeneralNotificationsData(data["notifications"]);
		}
		if(data.general_msg_type == 3) {
			handleNewGeneralNotificationsData(data["notifications"]);
		}
		if(data.general_msg_type == 4) {
			setUnseenGeneralNotificationsCount(data["count"]);
		}
		if(data.general_msg_type == 5) {
			updateGeneralNotificationDiv(data["notification"]);
		}

		if(data.chat_msg_type == 10) {
			console.info(data["notifications"]);
			handleChatNotificationsData(data["notifications"], data["new_page_number"]);
		}
		if(data.chat_msg_type == 11) {
			setChatPaginationExhaust();
		}
		if(data.chat_msg_type == 13) {
			handleNewChatNotificationsData(data["notifications"]);
		}
		if(data.chat_msg_type == 14) {
			setChatNotificationsCount(data["count"]);
		}
	}

	ws_notification.onopen = function(event) {
		console.log("WS Notification OPENED");
		setupGeneralNotificationsMenu();
		getFirstGeneralNotificationsPage();
		getUnseenGeneralNotificationsCount();

		setupChatNotificationsMenu();
		getFirstChatNotificationsPage();
	}

	ws_notification.onclose = function(event) {
		console.info("WS Notification CLOSED",event);
	}

	ws_notification.onerror = function(event) {
		console.error("WS Notification ERR", event);
	}

	if(ws_notification.readyState == ws_notification.OPEN) {
		console.log("WS Notification OPEN CMP");
	}
	if(ws_notification.readyState == ws_notification.CONNECTING) {
		console.log("WS Notification Conn...");
	}

	function executeQuery() {
		var query = ""
		query = document.getElementById('id_q_small').value;
		if (query == ""){
			query = document.getElementById('id_q_large').value;
		}
	    window.location.replace("{% url 'search' %}?q=" + query);
	    return false;
	}
</script>